source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DCTypography_Example', :exclusive => true do
  pod 'DCTypography', :path => '../'
end

target 'DCTypography_Tests', :exclusive => true do
  pod 'DCTypography', :path => '../'

  
end
